#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 04, 2021 09:37:30 AM IST  platform: Linux

import sys
import urllib.request
import sqlite3
import json
from tkinter import messagebox
import datetime
x = datetime.datetime.now()
today = x.strftime("%d%m%Y")
filenam = "data/" + today + ".json"
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def download():
    url = urllib.request.urlopen("https://api.apify.com/v2/key-value-stores/toDWvRj1JpTXiM8FF/records/LATEST?disableRedirect=true")
    s = url.read()
    fileopen = open(filenam, 'wb')
    fileopen.write(s)
    fileopen.close()
    tk.messagebox.showinfo(message="Downloaded successfully! Proceed to upload data.")
