#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 04, 2021 09:37:30 AM IST  platform: Linux

import sys
import urllib.request
import sqlite3
import json
from tkinter import messagebox
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import firsttest
    firsttest.vp_start_gui()

def download():
    url = urllib.request.urlopen("https://api.apify.com/v2/key-value-stores/toDWvRj1JpTXiM8FF/records/LATEST?disableRedirect=true")
    s = url.read()
    fileopen = open("data.json", 'wb')
    fileopen.write(s)
    fileopen.close()
    tk.messagebox.showinfo(message="Downloaded successfully! Proceed to upload data.")
def convert():
    conn = sqlite3.connect('uacDataDB')
    c = conn.cursor()

    #Table creation if not exists
    c.execute('CREATE TABLE IF NOT EXISTS cases(region text, totalInfected integer, newInfected integer, recovered integer, newRecovered integer, deceased integer, newDeceased integer)')

    #Convert Json in SQLite
    jd = json.load(open('data.json'))
    for n in jd['regionData']:
        c.execute("INSERT INTO cases VALUES(?, ?, ?, ?, ?, ?, ?)", [n['region'], n['totalInfected'], n['newInfected'], n['recovered'], n['newRecovered'], n['deceased'], n['newDeceased']])
    tk.messagebox.showinfo(message="Converted successfully! Restart the program to reflect new data.")
    #Committing and closing after queries
    conn.commit()
    conn.close()
